const data = [
  {
    id: 1,
    first_name: "Brad",
    last_name: "Gammett",
    email: "bgammett0@washington.edu",
    Currency: "Euro",
  },
  {
    id: 2,
    first_name: "Marven",
    last_name: "Prawle",
    email: "mprawle1@dedecms.com",
    Currency: "Yuan Renminbi",
  },
  {
    id: 3,
    first_name: "Brandais",
    last_name: "Rennock",
    email: "brennock2@alexa.com",
    Currency: "Yuan Renminbi",
  },
  {
    id: 4,
    first_name: "Katina",
    last_name: "Likly",
    email: "klikly3@usgs.gov",
    Currency: "Quetzal",
  },
  {
    id: 5,
    first_name: "Kelley",
    last_name: "Pearse",
    email: "kpearse4@cdc.gov",
    Currency: "Dollar",
  },
  {
    id: 6,
    first_name: "Clare",
    last_name: "Benitti",
    email: "cbenitti5@biglobe.ne.jp",
    Currency: "Krone",
  },
  {
    id: 7,
    first_name: "Cathlene",
    last_name: "Henniger",
    email: "chenniger6@scientificamerican.com",
    Currency: "Rupiah",
  },
  {
    id: 8,
    first_name: "Maggy",
    last_name: "Redding",
    email: "mredding7@amazon.co.jp",
    Currency: "Krona",
  },
  {
    id: 9,
    first_name: "Lotty",
    last_name: "Evequot",
    email: "levequot8@blogs.com",
    Currency: "Euro",
  },
  {
    id: 10,
    first_name: "Haleigh",
    last_name: "Cust",
    email: "hcust9@howstuffworks.com",
    Currency: "Ruble",
  },
  {
    id: 11,
    first_name: "Danice",
    last_name: "Steddall",
    email: "dsteddalla@chron.com",
    Currency: "Franc",
  },
  {
    id: 12,
    first_name: "Dorrie",
    last_name: "O'Crigane",
    email: "docriganeb@stumbleupon.com",
    Currency: "Won",
  },
  {
    id: 13,
    first_name: "Hershel",
    last_name: "Kleinmann",
    email: "hkleinmannc@elpais.com",
    Currency: "Yuan Renminbi",
  },
  {
    id: 14,
    first_name: "Ring",
    last_name: "Kraft",
    email: "rkraftd@amazonaws.com",
    Currency: "Peso",
  },
  {
    id: 15,
    first_name: "Anthony",
    last_name: "Filppetti",
    email: "afilppettie@reddit.com",
    Currency: "Gourde",
  },
  {
    id: 16,
    first_name: "Stephine",
    last_name: "Gerger",
    email: "sgergerf@mozilla.org",
    Currency: "Yuan Renminbi",
  },
  {
    id: 17,
    first_name: "Cyrille",
    last_name: "Grave",
    email: "cgraveg@vimeo.com",
    Currency: "Ruble",
  },
  {
    id: 18,
    first_name: "Munmro",
    last_name: "Margetson",
    email: "mmargetsonh@woothemes.com",
    Currency: "Rupiah",
  },
  {
    id: 19,
    first_name: "Brose",
    last_name: "Grigoryev",
    email: "bgrigoryevi@harvard.edu",
    Currency: "Baht",
  },
  {
    id: 20,
    first_name: "Allard",
    last_name: "Harriagn",
    email: "aharriagnj@microsoft.com",
    Currency: "Rupiah",
  },
  {
    id: 21,
    first_name: "Virgina",
    last_name: "Baitman",
    email: "vbaitmank@deviantart.com",
    Currency: "Krona",
  },
  {
    id: 22,
    first_name: "Cirillo",
    last_name: "Guthrum",
    email: "cguthruml@washington.edu",
    Currency: "Euro",
  },
  {
    id: 23,
    first_name: "Eamon",
    last_name: "MacGorley",
    email: "emacgorleym@opera.com",
    Currency: "Shilling",
  },
  {
    id: 24,
    first_name: "Cassandre",
    last_name: "Mc Trusty",
    email: "cmctrustyn@multiply.com",
    Currency: "Dinar",
  },
  {
    id: 25,
    first_name: "Becca",
    last_name: "Knowlton",
    email: "bknowltono@cdbaby.com",
    Currency: "Dinar",
  },
  {
    id: 26,
    first_name: "Birk",
    last_name: "Marwood",
    email: "bmarwoodp@desdev.cn",
    Currency: "Krona",
  },
  {
    id: 27,
    first_name: "Corabelle",
    last_name: "Cordaroy",
    email: "ccordaroyq@prlog.org",
    Currency: "Rupiah",
  },
  {
    id: 28,
    first_name: "Allina",
    last_name: "Stenner",
    email: "astennerr@hatena.ne.jp",
    Currency: "Euro",
  },
  {
    id: 29,
    first_name: "Hildegarde",
    last_name: "Saundercock",
    email: "hsaundercocks@newyorker.com",
    Currency: "Hryvnia",
  },
  {
    id: 30,
    first_name: "Bibbie",
    last_name: "Picknett",
    email: "bpicknettt@slate.com",
    Currency: "Yuan Renminbi",
  },
  {
    id: 31,
    first_name: "Francisco",
    last_name: "Palphramand",
    email: "fpalphramandu@bluehost.com",
    Currency: "Peso",
  },
  {
    id: 32,
    first_name: "Felicia",
    last_name: "Wolfendell",
    email: "fwolfendellv@twitpic.com",
    Currency: "Peso",
  },
  {
    id: 33,
    first_name: "Aurilia",
    last_name: "O' Timony",
    email: "aotimonyw@xrea.com",
    Currency: "Dong",
  },
  {
    id: 34,
    first_name: "Willyt",
    last_name: "Arnatt",
    email: "warnattx@slashdot.org",
    Currency: "Euro",
  },
  {
    id: 35,
    first_name: "Barrie",
    last_name: "Van De Cappelle",
    email: "bvandecappelley@barnesandnoble.com",
    Currency: "Yuan Renminbi",
  },
  {
    id: 36,
    first_name: "Melodee",
    last_name: "Pilbury",
    email: "mpilburyz@walmart.com",
    Currency: "Ruble",
  },
  {
    id: 37,
    first_name: "Augustus",
    last_name: "Dronsfield",
    email: "adronsfield10@nationalgeographic.com",
    Currency: "Somoni",
  },
  {
    id: 38,
    first_name: "Andrea",
    last_name: "Monckton",
    email: "amonckton11@mail.ru",
    Currency: "Peso",
  },
  {
    id: 39,
    first_name: "Cary",
    last_name: "Howler",
    email: "chowler12@infoseek.co.jp",
    Currency: "Euro",
  },
  {
    id: 40,
    first_name: "Erl",
    last_name: "Guthrum",
    email: "eguthrum13@delicious.com",
    Currency: "Yuan Renminbi",
  },
  {
    id: 41,
    first_name: "Brod",
    last_name: "Siddons",
    email: "bsiddons14@mapquest.com",
    Currency: "Dollar",
  },
  {
    id: 42,
    first_name: "Donavon",
    last_name: "Vreede",
    email: "dvreede15@goo.ne.jp",
    Currency: "Euro",
  },
  {
    id: 43,
    first_name: "Reena",
    last_name: "Sidery",
    email: "rsidery16@merriam-webster.com",
    Currency: "Yen",
  },
  {
    id: 44,
    first_name: "My",
    last_name: "Tregidga",
    email: "mtregidga17@quantcast.com",
    Currency: "Dollar",
  },
  {
    id: 45,
    first_name: "Caz",
    last_name: "Roulston",
    email: "croulston18@digg.com",
    Currency: "Shilling",
  },
  {
    id: 46,
    first_name: "Jorry",
    last_name: "Toffetto",
    email: "jtoffetto19@hp.com",
    Currency: "Real",
  },
  {
    id: 47,
    first_name: "Dennie",
    last_name: "Braunton",
    email: "dbraunton1a@scribd.com",
    Currency: "Euro",
  },
  {
    id: 48,
    first_name: "Ruben",
    last_name: "Coey",
    email: "rcoey1b@privacy.gov.au",
    Currency: "Yuan Renminbi",
  },
  {
    id: 49,
    first_name: "Bradney",
    last_name: "Fettes",
    email: "bfettes1c@wikispaces.com",
    Currency: "Yuan Renminbi",
  },
  {
    id: 50,
    first_name: "Zachery",
    last_name: "Robard",
    email: "zrobard1d@ihg.com",
    Currency: "Tugrik",
  },
];
const ids = [
  {
    id: 1,
    name: "Savina Vernall",
  },
  {
    id: 2,
    name: "Yoshi Cownden",
  },
  {
    id: 3,
    name: "Matilda Barrim",
  },
  {
    id: 4,
    name: "Joy Tidman",
  },
  {
    id: 5,
    name: "Willie Wheaton",
  },
  {
    id: 6,
    name: "Elihu Blumire",
  },
  {
    id: 7,
    name: "Jennette Quartermain",
  },
  {
    id: 8,
    name: "Marleen Brogden",
  },
  {
    id: 9,
    name: "Jasmin Ollington",
  },
  {
    id: 10,
    name: "Koralle McGilvary",
  },
];

module.exports = { data,ids};
